services:
  memoriai:
    image: tessaayv8/memoriai-assignment5:latest   # ✅ Docker Hub'daki yeni imaj
    # Eğer hocanın kendi bilgisayarında build etmesini de istiyorsan:
    # build: .
    container_name: memoriai-assignment5
    ports:
      - "8501:8501"          # Streamlit UI veya FastAPI portu
    env_file:
      - .env                 # .env içindeki DB + ML secrets
    volumes:
      - ./src/logs:/app/src/logs   # Log dosyalarını host'tan görebilmek için
    restart: unless-stopped
